# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170919_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsAnswer',
            new_name='ProductAnswer',
        ),
        migrations.AlterModelOptions(
            name='productquestion',
            options={'verbose_name_plural': 'Product Questions'},
        ),
    ]
