# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170919_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productanswer',
            old_name='anwser',
            new_name='answer',
        ),
    ]
